### ISSUE TITLE
EL8 support / 4.18 kernel 

### ISSUE THREAD

**Issue by rodehoed** [veeam/blksnap#17]
Hi,

This one is little sales related :-) In the past we had Veeam reviewed and it was not fitting our needs (Linux was not first class citizen at that time). 

Currently we are using R1soft (hcpdriver) which also works similar like blksnap.  Their driver is closed source and has some issues with the latest LTS kernels (4.18 and 5.1). So an upstreamed (or at least opensource) kernel module would be a big win for us and would make Veeam a possible option for us. 

Question is, will 5.10 the lowest kernel supported? Or will 4.18 be supported too in the future.

**Comment by Fantu** [comment]
I think that add support for kernel < 5.10 it would take away time that would be better spent improving blksnap enough to be accepted upstream faster.
However, only one of the developers will be able to give you a certain answer, I only give a very small contribution to this project to try to speed up the upstream kernel integration and the possible integration in debian and derivatives.

5.10 is an LTS version and 5.15 also, relating to upstream LTS (the best maintained): https://kernel.org/category/releases.html
there are additional LTS version that are distro specific and maintained only by the distro team.

**Comment by Fantu** [comment]
useful information: veeam agent for linux 6.0 was released and support kernel from version 2.6.32 to version 6.1 (should use veeamsnap for older kernel and blksnap for newer)
https://www.veeam.com/veeam_agent_linux_6_0_release_notes_rn.pdf

**Comment by SergeiShtepa** [comment]
The main task of the blksnap module is to make an upstream version.
The veeamsnap module works fine on older versions.
