### ISSUE TITLE
Freeze on blksnap tests on ubuntu 20.04 with kernel 5.15

### ISSUE THREAD

**Issue by Fantu** [veeam/blksnap#23]
Hi, on latest version I did 2 fast test, one building kernel 6.1-rc6 with v2 patch for upstream on debian Sid (unstable) vm was ok, another on my notebook with ubuntu 20.04 and kernel 5.15 (from ubuntu package) and blksnap module from git and the system frezeed on blksnap tests.
the log of blksnap tests: https://paste.debian.net/1262187/
and kern.log part that I think related to the issue: https://paste.debian.net/1262189/
@SergeiShtepa tell me if you need full kern.log instead

**Comment by Fantu** [comment]
@SergeiShtepa sorry, I missed the decoded output (using scripts/decode_stacktrace.sh from kernel git) : https://paste.debian.net/1262193/

**Comment by SergeiShtepa** [comment]
Thanks. I took it to work. I think these logs are enough.

**Comment by SergeiShtepa** [comment]
Funny. I've already fixed this bug in the patch, but I forgot to move it to the master branch.

**Comment by Fantu** [comment]
@SergeiShtepa thanks, I did some fast tests now and no freeze anymore but gave some error, about unload of module fails I tried to add some sleep https://github.com/Fantu/blksnap/commit/ae8aa53f11568018d628ab0fc633dc1050c79122
but there was other error when seems that there is some operation still running when arrive to unload so I suppose there is something wrong, here the logs: https://paste.debian.net/1262321/

**Comment by SergeiShtepa** [comment]
```
Destroy snapshot c1e48299-dcee-4dc7-8391-4d043bdaf66a
Waiting for streach process terminate
Unload module
modprobe: FATAL: Module blksnap is in use.
[TBD]Failed to get event from snapshot.: No such process
Stretch snapshot service failed.
```
Yes. Two processes work with the module. Synchronization in the test may be required. I'll look at it later.
Work on creating documentation.

**Comment by Fantu** [comment]
@SergeiShtepa thanks for your works, "merging window" for kernel 6.2 should start in 1-2 weeks and I hope the v3 will be get more attention (and I also hope approval if it is already good enough)

**Comment by Fantu** [comment]
@SergeiShtepa I noticed some additional commit of some weeks ago in VAL-6.0 branch: https://github.com/veeam/blksnap/compare/VAL-6.0
also merging them is forgotten or need more testing before merge to master?

**Comment by SergeiShtepa** [comment]
Yes, there are some changes in VAL-6.0.
I'm planning to move something to the master branch. But not all of them.
