### ISSUE TITLE
Emphasis risk of `blksnap snapshot_appendstorage -f`

### ISSUE THREAD

**Issue by buczek** [veeam/blksnap#53]
### Description

When `blksnap snapshot_appendstorage -f` is used, the blocks currently allocated to the named file are given to the snapshot to be used as difference storage. The file is not locked in any way, so there is a risk of corruption for the containing file system if the mapping of the file is modified, for example, when the file is deleted while the blocks are still in use as a difference storage.

This is just an assumption from looking at the code. Please correct me, if I'm wrong here.

If true, however, I suggest to add a warning to the documentation and to the usage messages from the tool itself, because the user might be unaware of the risk.

### Usage tips

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into this.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this.
* Subscribe to receive notifications on status change and new comments, you can do also without add comment.

**Comment by buczek** [comment]
Sorry, I'm not 100% what you mean by "A description of this problem would also be helpful". :-)

Are you asking me to provide more information to better describe the problem, I've made this enhancement suggestion for, or do you just acknowledge the fact, that the documentation should describe the problem?

**Comment by SergeiShtepa** [comment]
Hi.

I'm just acknowledging the fact that the documentation should describe the problem.
There is clearly not enough documentation yet.
I apologize for not expressing my thought accurately enough.

I have planned to work on the problem you described. But the priority level of the task for finalizing documentation is still somewhat lower than, for example, tests. The test coverage is clearly insufficient. Now I'm trying to concentrate my efforts on the tests.

I am grateful to you for the work you have already done, which has already made the blksnap module better.
