### ISSUE TITLE
blksnap - RIP

### ISSUE THREAD

**Issue by brolal** [veeam/blksnap#77]
### Distribution

red hat 9

### Architecture

x64

### Kernel version

5.14.0

### Blksnap version

6.0.3.1221

### Bug description

the build doesnt work, shit docs, shit software for linux, as always 

### Steps to reproduce

try download it and build it

### Expected behavior

to work coz I pay a license 

### Additional information

its shit

**Comment by Fantu** [comment]
hi, without giving any information about the problem it is impossible to help you or if there is a bug in blksnap find it and fix it

**Comment by SergeiShtepa** [comment]
Good day, @brolal .
Please contact the official technical support. Specialists will help you prepare the necessary logs and other information.
At the moment, I can only say that the VAL 6.0.3 product includes a package with a kernel module pre-build for EL9. The package also contains a special `blksnap-loader` script that ensures the safe loading of the module. 
Please read the documentation and consult with technical support.
