### ISSUE TITLE
Error Invalid argument when I execute attach -device

### ISSUE THREAD

**Issue by josehrz910322** [veeam/blksnap#90]
### Distribution

 Ubuntu 22.04

### Architecture

x86_64

### Kernel version

6.5.0-45-generic

### Blksnap version

Master from github repository

### Bug description

I am trying to execute blksnap from the terminal but when I execute the following command 

`sudo blksnap attach -d /dev/sda2`

I get the following error 

Failed to attach filter to the block device: Invalid argument

### Steps to reproduce

To compile and install the project I execute the following instructions:

`git clone https://github.com/veeam/blksnap.git`
`sudo apt install g++ cmake uuid-dev libboost-program-options-dev libboost-filesystem-dev libssl-dev debhelper`
`cd ./pkg/deb`
`./build-blksnap.sh`

after compilation, I got the packages 

1. blksnap-dev_amd64.deb
2. blksnap-tools_amd64.deb
3. blksnap-tests_amd64.deb

I install each one with 

sudo apt install

I also try to debug the source code and the error happens in the class CDeviceCtl code line 120 and file /tools/blksnap/main.cpp

`unsigned int Ioctl(const unsigned int cmd, void *param)
        {
            int ret = ::ioctl(m_fd, cmd, param);
            if (ret < 0)
                throw std::system_error(errno, std::generic_category());
            return static_cast<unsigned int>(ret);
        }`

I have noticed that in the call to the ioctl method, BLKFILTER_ATTACH is passed as an argument, which is defined in the header file blk-filter.h, so it makes me think that I need to install some additional module, but I do not know what it is.

### Additional information

Additionally, I tried to compile the Release_6.1.2.1781, VAL-6.2 and VAL-7 versions, but after installing the packages and running the following command

`I get the error message Command is not set.`

I would like if anyone has a solution
Any thoughts will be greatly appreciated.

Best.

**Comment by Fantu** [comment]
Hi, blksnap tool from master branch is only for latest kernel module for upstream, as you can see from readme, until will be accepted upstream will be not easy/fast use it on any kernel but only the version from latest @SergeiShtepa work, if you want to use blksnap easy and fast for older kernel you should install both tool and external kernel module from the same branch (if you hadn't already done it with VAL-6.2 or VAL-7).

**Comment by SergeiShtepa** [comment]
Hi!

Thank you @Fantu  for your comment!
Yes, @josehrz910322, in order for the blksnap-tools and libraries to work, you need support from the kernel. The blksnap module is needed. There is no blksnap module in the upstream kernel yet. We are working on it. You can see the latest patch for the kernel [here](https://github.com/veeam/blksnap/tree/master/patches/lk6.9).

But if you want to use the out-of-tree version of the module, then you can build the project from the branch [VAL-6.1.2](https://github.com/veeam/blksnap/tree/VAL-6.1.2) .
The project from the branch [VAL-6.2](https://github.com/veeam/blksnap/tree/VAL-6.2) has support for the latest kernel and is preparing for release.
The project from the branch [VAL-7.0](https://github.com/veeam/blksnap/tree/VAL-7.0) is in a state of development and testing. I'll be glad if you report bugs for this code.
